---
abstract: 'automatically reload static assets'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Mojo-AssetReloader
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Cwd: '0'
  Exporter: '5'
  File::Basename: '0'
  Filesys::Notify::Simple: '0'
  Filter::signatures: '0.09'
  Getopt::Long: '0'
  Mojolicious: '0'
  Thread::Queue: '0'
  perl: '5.010'
resources:
  repository: git://github.com/Corion/App-Mojo-AssetReloader.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
